# These are supported funding model platforms

ko_fi: peterumezaki

# GitHub Sponsors (to be added later once approved)
# github: umezakip

# Other options you can add later if needed:
# patreon: # Replace with a single Patreon username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
